# Generated by Django 5.0.2 on 2024-02-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
